sudo: required

language: python

matrix:
  include:
    - osx
      language: generic
      python: "2.7"

    - linux
      sudo: required
      python: "2.7"
      dist: trusty
  
services:
  - mysql

python:
  - 2.7

before_install:
  - sudo mysql -e 'CREATE DATABASE devops;'

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
