sudo: required

language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      services: mysql
    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 2.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 2.7.15
        - python -m pip install --upgrade pip
      env: PATH=/c/Python27/c/Python27/Scripts:$PATH

before_install:
  - sudo mysql -e 'CREATE DATABASE devops;'

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
