sudo: required

language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      services:
        - mysql
      before_install:
        - sudo mysql -e 'CREATE DATABASE devops;'

    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - brew install 'mysql@5.7'
        - brew services start 'mysql@5.7'
        - brew install python
        - mysql -e 'CREATE DATABASE devops;'

    - name: "Python 2.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python2
        - choco install mysql
        - choco install -y --allow-empty-checksums pip
        - mysql -e 'CREATE DATABASE devops;'
      env: PATH=/c/Python27:/c/Python27/Scripts:/c/tools/mysql/current/bin:$PATH

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
