sudo: required

language: python

services:
  - mysql

python:
  - 2.7

before_install:
  - sudo mysql -e 'CREATE DATABASE devops;'

install:
  - pip install MySQL-python paramiko psutil Django-1.9

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
