name: Django CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up MySQL 5.7
      uses: mirromutth/mysql-action@master
      with:
        mysql version: 5.7
        mysql database: devops
        mysql root password: 123456
    - name: pip requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Django Migrations
      run: |
        mysql -u root -p123456 -h127.0.0.1 -e 'CREATE DATABASE devops;'
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Test
      run: |
        python manage.py test
