name: Django CI
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Mysql
      run: |
        apt-get install mysql-server
        apt-get install mysql-client
        apt-get install libmysqlclient-dev
    - name: Django Migrations
      run: |
        service mysql start
        mysql -u root -e 'CREATE DATABASE devops;'
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Test
      run: |
        python manage.py test
