name: Django CI
on:
  push:
    branches:
      - master
jobs:
  build:
    run-on: ubuntu-latest
  services:
    - mysql  
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup python
        uses: actions/setup-node@v1
        with:
          python-version: "2.7"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
        
      - name: Run Tests
        run: |
          python manage.py test
